#!/usr/bin/env sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

(
    cd $DIR/..
    rm -rf build
    mkdir -p build
    cd build
    cmake -D CMAKE_PREFIX_PATH=$(brew --prefix qt5) -D CMAKE_BUILD_TYPE=Release ../
    make
)
